# 과제 - Human Activity Reconition

- 결정트리
- SVC
- 앙상블

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

- 훈련 / 테스트 데이터셋 불러오기

In [77]:
train_df = pd.read_csv('train.csv')
train_df.head()

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  tBodyAcc-std()-X  \
0           0.288585          -0.020294          -0.132905         -0.995279   
1           0.278419          -0.016411          -0.123520         -0.998245   
2           0.279653          -0.019467          -0.113462         -0.995380   
3           0.279174          -0.026201          -0.123283         -0.996091   
4           0.276629          -0.016570          -0.115362         -0.998139   

   tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  tBodyAcc-mad()-Y  \
0         -0.983111         -0.913526         -0.995112         -0.983185   
1         -0.975300         -0.960322         -0.998807         -0.974914   
2         -0.967187         -0.978944         -0.996520         -0.963668   
3         -0.983403         -0.990675         -0.997099         -0.982750   
4         -0.980817         -0.990482         -0.998321         -0.979672   

   tBodyAcc-mad()-Z  tBodyAcc-max()-X  ...  fBodyBodyGyroJerkMag-kurtosis()  \
0         -0.923527         -0.934724  ...                        -0.710304   
1         -0.957686         -0.943068  ...                        -0.861499   
2         -0.977469         -0.938692  ...                        -0.760104   
3         -0.989302         -0.938692  ...                        -0.482845   
4         -0.990441         -0.942469  ...                        -0.699205   

   angle(tBodyAccMean,gravity)  angle(tBodyAccJerkMean),gravityMean)  \
0                    -0.112754                              0.030400   
1                     0.053477                             -0.007435   
2                    -0.118559                              0.177899   
3                    -0.036788                             -0.012892   
4                     0.123320                              0.122542   

   angle(tBodyGyroMean,gravityMean)  angle(tBodyGyroJerkMean,gravityMean)  \
0                         -0.464761                             -0.018446   
1                         -0.732626                              0.703511   
2                          0.100699                              0.808529   
3                          0.640011                             -0.485366   
4                          0.693578                             -0.615971   

   angle(X,gravityMean)  angle(Y,gravityMean)  angle(Z,gravityMean)  subject  \
0             -0.841247              0.179941             -0.058627        1   
1             -0.844788              0.180289             -0.054317        1   
2             -0.848933              0.180637             -0.049118        1   
3             -0.848649              0.181935             -0.047663        1   
4             -0.847865              0.185151             -0.043892        1   

   Activity  
0  STANDING  
1  STANDING  
2  STANDING  
3  STANDING  
4  STANDING  

[5 rows x 563 columns]

In [12]:
test_df = pd.read_csv('test.csv')
test_df.head()

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  tBodyAcc-std()-X  \
0           0.257178          -0.023285          -0.014654         -0.938404   
1           0.286027          -0.013163          -0.119083         -0.975415   
2           0.275485          -0.026050          -0.118152         -0.993819   
3           0.270298          -0.032614          -0.117520         -0.994743   
4           0.274833          -0.027848          -0.129527         -0.993852   

   tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  tBodyAcc-mad()-Y  \
0         -0.920091         -0.667683         -0.952501         -0.925249   
1         -0.967458         -0.944958         -0.986799         -0.968401   
2         -0.969926         -0.962748         -0.994403         -0.970735   
3         -0.973268         -0.967091         -0.995274         -0.974471   
4         -0.967445         -0.978295         -0.994111         -0.965953   

   tBodyAcc-mad()-Z  tBodyAcc-max()-X  ...  fBodyBodyGyroJerkMag-kurtosis()  \
0         -0.674302         -0.894088  ...                        -0.705974   
1         -0.945823         -0.894088  ...                        -0.594944   
2         -0.963483         -0.939260  ...                        -0.640736   
3         -0.968897         -0.938610  ...                        -0.736124   
4         -0.977346         -0.938610  ...                        -0.846595   

   angle(tBodyAccMean,gravity)  angle(tBodyAccJerkMean),gravityMean)  \
0                     0.006462                              0.162920   
1                    -0.083495                              0.017500   
2                    -0.034956                              0.202302   
3                    -0.017067                              0.154438   
4                    -0.002223                             -0.040046   

   angle(tBodyGyroMean,gravityMean)  angle(tBodyGyroJerkMean,gravityMean)  \
0                         -0.825886                              0.271151   
1                         -0.434375                              0.920593   
2                          0.064103                              0.145068   
3                          0.340134                              0.296407   
4                          0.736715                             -0.118545   

   angle(X,gravityMean)  angle(Y,gravityMean)  angle(Z,gravityMean)  subject  \
0             -0.720009              0.276801             -0.057978        2   
1             -0.698091              0.281343             -0.083898        2   
2             -0.702771              0.280083             -0.079346        2   
3             -0.698954              0.284114             -0.077108        2   
4             -0.692245              0.290722             -0.073857        2   

   Activity  
0  STANDING  
1  STANDING  
2  STANDING  
3  STANDING  
4  STANDING  

[5 rows x 563 columns]

In [61]:
from sklearn.preprocessing import StandardScaler
train_std = StandardScaler().fit_transform(train_df.values[:,:-1])
test_std = StandardScaler().fit_transform(test_df.values[:,:-1])

- 훈련 데이터와 테스트 데이터 설정 (훈련 데이터와 테스트 데이터가 이미 분류되어있기 때문에)

In [62]:
X_train = train_std
y_train = train_df.values[:,-1]
X_test = test_std
y_test = test_df.values[:,-1]

In [31]:
np.unique(y_train, return_counts=True)

(array(['LAYING', 'SITTING', 'STANDING', 'WALKING', 'WALKING_DOWNSTAIRS',
        'WALKING_UPSTAIRS'], dtype=object),
 array([1407, 1286, 1374, 1226,  986, 1073], dtype=int64))

#### 결정트리 (DecisionTreeClassifier)

In [32]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(random_state=2021)
dtc.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'random_state': 2021,
 'splitter': 'best'}

In [33]:
params = {
    'max_depth' : [2, 3, 4, 5, 6],
    'min_samples_split' : [2, 3, 4]
}

In [34]:
from sklearn.model_selection import GridSearchCV

grid_dt = GridSearchCV(
    dtc, param_grid=params, scoring='accuracy', cv=5
)

In [35]:
grid_dt.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=2021),
             param_grid={'max_depth': [2, 3, 4, 5, 6],
                         'min_samples_split': [2, 3, 4]},
             scoring='accuracy')

In [37]:
grid_dt.best_params_

{'max_depth': 5, 'min_samples_split': 2}

In [38]:
best_clf = grid_dt.best_estimator_

In [39]:
dtc_acc = best_clf.score(X_test, y_test)
dtc_acc

0.839497794367153

#### SVC (Support Vector Machine)

In [40]:
from sklearn.svm import SVC
svc = SVC(random_state=2021)
svc.get_params()

{'C': 1.0,
 'break_ties': False,
 'cache_size': 200,
 'class_weight': None,
 'coef0': 0.0,
 'decision_function_shape': 'ovr',
 'degree': 3,
 'gamma': 'scale',
 'kernel': 'rbf',
 'max_iter': -1,
 'probability': False,
 'random_state': 2021,
 'shrinking': True,
 'tol': 0.001,
 'verbose': False}

In [41]:
params = {'C': [0.01, 0.1, 1, 10, 100]}

In [42]:
grid_sv = GridSearchCV(svc, param_grid=params, scoring='accuracy', cv=5)
grid_sv.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=SVC(random_state=2021),
             param_grid={'C': [0.01, 0.1, 1, 10, 100]}, scoring='accuracy')

In [43]:
grid_sv.best_params_

{'C': 100}

In [44]:
params = {'C': [100, 500, 1000, 1500, 2000, 2500]}
grid_sv = GridSearchCV(svc, param_grid=params, scoring='accuracy', cv=5)
grid_sv.fit(X_train, y_train)
grid_sv.best_params_

{'C': 100}

In [45]:
params = {'C': [50, 75, 100, 125, 150, 200, 250]}
grid_sv = GridSearchCV(svc, param_grid=params, scoring='accuracy', cv=5)
grid_sv.fit(X_train, y_train)
grid_sv.best_params_

{'C': 75}

In [46]:
params = {'C': [65, 70, 75, 80, 85]}
grid_sv = GridSearchCV(svc, param_grid=params, scoring='accuracy', cv=5)
grid_sv.fit(X_train, y_train)
grid_sv.best_params_

{'C': 75}

In [47]:
best_svc = grid_sv.best_estimator_
svc_acc = best_svc.score(X_test, y_test)
svc_acc

0.9477434679334917

#### 앙상블 (Ensemble)

- 하드보팅 (Hard Voting)

In [48]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

In [73]:
lrc = LogisticRegression(max_iter=8000)
svc2 = SVC(max_iter=8000)
knn = KNeighborsClassifier()

In [74]:
from sklearn.ensemble import VotingClassifier

voc = VotingClassifier(
    estimators=[('LRC',lrc),('SVC',svc2),('KNN',knn)], voting='hard'
)

In [75]:
voc.fit(X_train, y_train)
voc_hv_acc = voc.score(X_test, y_test)
voc_hv_acc

0.9613165931455717

- 소프트보팅 (Soft Voting)

In [80]:
svc3 = SVC(probability=True, max_iter=8000)
svc3.fit(X_train, y_train)
svc3.predict_proba(X_test[:5])

array([[5.44656114e-07, 1.09206621e-06, 9.99733013e-01, 6.11994274e-05,
        9.12361173e-05, 1.12914803e-04],
       [6.28208004e-04, 5.26199323e-02, 9.46509848e-01, 9.63797080e-05,
        6.74801008e-05, 7.81514780e-05],
       [2.65258325e-04, 2.67553093e-03, 9.96656897e-01, 1.88645587e-04,
        1.25263081e-04, 8.84048055e-05],
       [2.61571296e-04, 1.98105355e-03, 9.97340121e-01, 1.64215667e-04,
        1.43037762e-04, 1.10000788e-04],
       [2.18699161e-07, 4.45684218e-07, 9.99920684e-01, 2.76928178e-05,
        2.69180896e-05, 2.40406946e-05]])

In [81]:
voc2 = VotingClassifier(
    estimators=[('LRC',lrc),('SVC',svc3),('KNN',knn)], voting='soft'
)

In [82]:
voc2.fit(X_train, y_train)
voc2.score(X_train, y_train)

0.9949673558215452

In [83]:
voc2.predict_proba(X_test[:5])

array([[1.09435397e-06, 8.60794488e-06, 9.99895541e-01, 1.98215163e-05,
        2.99602399e-05, 4.49747850e-05],
       [2.13019725e-04, 2.55523733e-02, 9.74149168e-01, 3.19522432e-05,
        2.26395688e-05, 3.08472120e-05],
       [1.03470957e-04, 2.44693557e-02, 9.75289550e-01, 6.29421932e-05,
        4.04585475e-05, 3.42226685e-05],
       [9.75357818e-05, 4.17936312e-03, 9.95579297e-01, 5.43685236e-05,
        4.68816092e-05, 4.25542864e-05],
       [1.94900739e-07, 1.09409114e-04, 9.99862935e-01, 9.07154500e-06,
        8.77268364e-06, 9.61699644e-06]])

- GridSearchCV 적용 (충분히 높은 정확도이지만 적용)

In [84]:
params = {
    'LRC__C' : [0.1, 1, 10],
    'SVC__C' : [0.1, 1, 10]
}

In [85]:
from sklearn.model_selection import GridSearchCV
grid_voc2 = GridSearchCV(voc2, param_grid=params, scoring='accuracy', cv=3)
grid_voc2.fit(X_train, y_train)
grid_voc2.best_params_

{'LRC__C': 10, 'SVC__C': 10}

In [96]:
params = {
    'LRC__C' : [5, 10, 100],
    'SVC__C' : [5, 10, 100]
}
grid_voc2 = GridSearchCV(voc2, param_grid=params, scoring='accuracy', cv=3)
grid_voc2.fit(X_train, y_train)
grid_voc2.best_params_

{'LRC__C': 100, 'SVC__C': 100}

In [97]:
params = {
    'LRC__C' : [50, 100, 150, 500],
    'SVC__C' : [50, 100, 150, 500]
}
grid_voc2 = GridSearchCV(voc2, param_grid=params, scoring='accuracy', cv=3)
grid_voc2.fit(X_train, y_train)
grid_voc2.best_params_

{'LRC__C': 150, 'SVC__C': 50}

In [95]:
voc_sv_acc = grid_voc2.best_estimator_.score(X_test, y_test)

AttributeError: 'GridSearchCV' object has no attribute 'best_estimator_'

## 최종결과 - 비교

In [ ]:
# 정확도 (accuracy)
print(f'DTC: {dtc_acc:.4f}, SVC: {svc_acc:.4f}, VOC(HV): {voc_hv_acc:.4f}, VOC(SV): {voc_sv_acc:.4f}')