# 데이터 전처리

### 1. 레이블 인코딩

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

In [ ]:
# 레이블 인코더 객체 생성
le = LabelEncoder()

In [ ]:
# 학습, 데이터를 훑어 봄
le.fit(items)

LabelEncoder()

In [ ]:
# 인코딩 실행
labels = le.transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [ ]:
# 실전에서는 fit과 transform을 한번에
le2 = LabelEncoder()
labels = le2.fit_transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [ ]:
# 고수들은 이렇게 안해요...! le2라는 변수를 만들 이유가 없다.
labels = LabelEncoder().fit_transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [ ]:
# method chaining
s = ' A quick brown fox '
s.lower().lstrip().rstrip().replace('a', 'the').replace('fox', 'wolf').split()

['the', 'quick', 'brown', 'wolf']

In [ ]:
le2.inverse_transform([4,5,2,3,0,1])

array(['전자렌지', '컴퓨터', '믹서', '선풍기', 'TV', '냉장고'], dtype='<U4')

### 2. One-hot encoding
- 그렇게 많이 사용하지는 않지만 딥러닝에서 신경망 부분에서 사용

In [ ]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()

In [ ]:
oh_labels = ohe.fit_transform(labels.reshape(-1, 1))
oh_labels

<8x6 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [ ]:
oh_labels.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

- reshape 공부

In [ ]:
import numpy as np
a = np.arange(24).reshape(4, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
a.reshape(2, -1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
a.reshape(2, -1, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a.reshape(2, 2, 2, 3)

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]],


       [[[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]]]])

#### 3. 표준화(Standaradization) - 표준정규분포로 변환

In [ ]:
from sklearn.datasets import load_iris
iris = load_iris()

In [ ]:
import pandas as pd
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
count         150.000000        150.000000         150.000000        150.000000
mean            5.843333          3.057333           3.758000          1.199333
std             0.828066          0.435866           1.765298          0.762238
min             4.300000          2.000000           1.000000          0.100000
25%             5.100000          2.800000           1.600000          0.300000
50%             5.800000          3.000000           4.350000          1.300000
75%             6.400000          3.300000           5.100000          1.800000
max             7.900000          4.400000           6.900000          2.500000

In [ ]:
from sklearn.preprocessing import StandardScaler
iris_std = StandardScaler().fit_transform(iris.data)

In [ ]:
df2 = pd.DataFrame(iris_std, columns=iris.feature_names)
df2.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
count       1.500000e+02      1.500000e+02       1.500000e+02      1.500000e+02
mean       -1.690315e-15     -1.842970e-15      -1.698641e-15     -1.409243e-15
std         1.003350e+00      1.003350e+00       1.003350e+00      1.003350e+00
min        -1.870024e+00     -2.433947e+00      -1.567576e+00     -1.447076e+00
25%        -9.006812e-01     -5.923730e-01      -1.226552e+00     -1.183812e+00
50%        -5.250608e-02     -1.319795e-01       3.364776e-01      1.325097e-01
75%         6.745011e-01      5.586108e-01       7.627583e-01      7.906707e-01
max         2.492019e+00      3.090775e+00       1.785832e+00      1.712096e+00

- Logistic Regression 으로 분류

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    iris.data, iris.target, stratify=iris.target, test_size=0.2, random_state=2021
)

In [ ]:
from sklearn.linear_model import LogisticRegression
lrc = LogisticRegression()
lrc.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [ ]:
# 표준정규분포로 변환된 데이터로 학습하면 에러가 발생하지 않음
X_train, X_test, y_train, y_test = train_test_split(
    iris_std, iris.target, stratify=iris.target, test_size=0.2, random_state=2021
)
lrc = LogisticRegression()
lrc.fit(X_train, y_train)

LogisticRegression()

In [ ]:
lrc.score(X_test, y_test)

0.9

In [ ]:
lrc.score(X_test, y_test)

0.9

In [ ]:
### 4. 정규화(Normalization) - 0 ~ 1 사이의 값으로 변환

In [ ]:
from sklearn.preprocessing import MinMaxScaler
iris_mm = MinMaxScaler().fit_transform(iris.data)

In [ ]:
df3 = pd.DataFrame(iris_mm, columns=iris.feature_names)
df3.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
count         150.000000        150.000000         150.000000        150.000000
mean            0.428704          0.440556           0.467458          0.458056
std             0.230018          0.181611           0.299203          0.317599
min             0.000000          0.000000           0.000000          0.000000
25%             0.222222          0.333333           0.101695          0.083333
50%             0.416667          0.416667           0.567797          0.500000
75%             0.583333          0.541667           0.694915          0.708333
max             1.000000          1.000000           1.000000          1.000000

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    iris_mm, iris.target, stratify=iris.target, test_size=0.2, random_state=2021
)
lrc = LogisticRegression()
lrc.fit(X_train, y_train)
lrc.score(X_test, y_test)

0.9